      - name: Проверка что Containerd установлен и перезагружен
        ansible.builtin.systemd:
            name: containerd
            state: restarted
            enabled: yes

      - name: Проверка что Containerd установлен и перезагружен
        ansible.builtin.systemd:
            name: kubelet
            state: restarted
            enabled: yes
            
      - name: Удаление swap с fstab
        ansible.builtin.lineinfile:
            path: '/etc/fstab'
            regexp: '\sswap\s'
            state: 'absent'

      - name: Добавление в hosts запись
        ansible.builtin.lineinfile:
            path: /etc/hosts
            line: | 
              192.168.31.10   kubmaster1
              192.168.31.11   kubmaster2
              192.168.31.12   kubmaster3
              192.168.31.13   kubworker1
              192.168.31.14   kubworker2
              192.168.31.15   kubworker3

      - name: Добавление параметров ядра для Kubernetes
        ansible.builtin.lineinfile:
            path: /etc/sysctl.d/kubernetes.conf
            line: |
              net.bridge.bridge-nf-call-ip6tables = 1
              net.bridge.bridge-nf-call-iptables = 1
              net.ipv4.ip_forward = 1
            create: yes
        
      - name: Добавление модулей ядра для Containerd 
        ansible.builtin.lineinfile:
            path: /etc/modules-load.d/containerd.conf
            line: |
              overlay
              br_netfilter
            create: yes

      - name: Настройка systemd в качестве cgroup
        ansible.builtin.shell: containerd config default | sudo tee /etc/containerd/config.toml >/dev/null 2>&1
        
      - name: Настройка systemd в качестве cgroup
        ansible.builtin.shell: sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
       
      - name: Перезагрузка
        reboot: