        - name: Добавление ключа Containerd
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Установка стабильного репозитория Containerd
          ansible.builtin.shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

        - name: Добавляем universe
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
            state: present

        - name: Добавление ключа Kubernetes
          apt_key:
            url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
            state: present
        
        - name: Установка стабильного репозитория Kubernetes
          ansible.builtin.apt_repository:
            repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
            state: present

        - name: Установка Containerd и компонентов Kubernetes
          ansible.builtin.apt:
            name:
              - apt-transport-https
              - ca-certificates
              - lsb-release
              - software-properties-common
              - libasound2
              - gnupg-agent
              - containerd.io
              - kubelet
              - kubeadm
              - kubectl
            update-cache: yes
            cache_valid_time: 86400
            
        - name: Отключение ufw
          ansible.builtin.systemd:
            name: ufw
            state: stopped
            enabled: false