version: "3"
services:
  lavagna:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: lavagna
    networks:
    - lavagnaNetwork
    ports:
    - 8080:8080
    environment:
      LAVAGNA_DB_HOST: Mysql
      LAVAGNA_DB_USER: exampleuser
      LAVAGNA_DB_PASSWORD: q1q1q1q1
      LAVAGNA_DB_NAME: exampledb
    depends_on:
    - Mysql
  Mysql:
    image: mysql:5.7
    restart: always
    networks:
    - lavagnaNetwork
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: q1q1q1q1
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
networks:
  lavagnaNetwork:
    driver: bridge

volumes:
  db:

