
- name: Установка пакетов для серверов Kubernetes
  become: yes
  hosts: kub_all
  roles:
    - role: centos_packages
      when: ansible_facts['distribution'] == "CentOS"
    - role: ubuntu_packages
      when: ansible_facts['distribution'] == "Ubuntu"

- name: Преконфиг серверов Kubernetes
  become: yes
  hosts: kub_all
  roles:
    - role: preconfig
      when: ansible_facts['distribution'] == "CentOS"
    - role: preconfig
      when: ansible_facts['distribution'] == "Ubuntu"

- name: Почти закончили щас самое главное
  become: yes
  hosts: kubmaster
  roles:
    - role: initialization
      when: ansible_facts['distribution'] == "CentOS"
    - role: initialization
      when: ansible_facts['distribution'] == "Ubuntu"