apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-viting-app
spec:
  containers:
  - name: voting-app
    image: dockersamples/examplevotingapp_worker
