apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    name: worker-deploy
    app: demo-viting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
      app: demo-viting-app
  template:
   metadata:
    name: worker-pod
    labels:
      name: worker-pod
      app: demo-viting-app
   spec:
    containers:
      - name: voting-app
        image: dockersamples/examplevotingapp_worker